### ISSUE TITLE
ERROR: Example Fails

### ISSUE THREAD

**Issue by morrica** [chonla/format#5]
This doesn't seem to work. The example given in the documentation fails with an error. I am not able to make it work with my code either.

Example:
```
var params = map[string]interface{}{
    "sister": "Susan",
    "brother": "Louis",
}
format.Printf("%<brother> loves %<sister>.", params)
```

Produces:
`%!<(MISSING)brother> loves %!<(MISSING)sister>.`

**Comment by chonla** [comment]
Looking into that.

**Comment by chonla** [comment]
@morrica It's an error in example in the README file. Fixed that.

Just put the format after `%<brother>` and `%<sister>`. The correct one should be like `%<brother>s` and `%<sister>s`.
